export const WEBSOCKET_PUBLIC_URL = "http://localhost:5505/"
export const WEBSOCKET_SERVER_PORT = 5505

const QUIZZ_CONFIG = {
  password: "PASSWORD",
  subject: "Tech Trivia",
  questions: [
    {
      question: "What does the .com in a website address usually mean?",
      answers: ["Computer", "Communication", "Commercial", "Community"],
      solution: 2,
      cooldown: 5,
      time: 20,
    },
    {
      question: "In computing, what is a “bit”?",
      answers: ["A programming language", "The smallest unit of data", "A type of virus", "A hardware device"],
      solution: 1,
      cooldown: 5,
      time: 20,
    },
    {
      question: "NASA might be your last hope to escape zombies; what does NASA stand for?",
      answers: ["National Aeronautics and Science Association", "National Aerospace and Space Agency", "National Astronautical and Space Agency", "National Aeronautics and Space Administration"],
      solution: 3,
      cooldown: 5,
      time: 20,
    },
    {
      question: "What is Hyperloop, the transportation concept being developed by multiple companies?",
      answers: ["Autonomous electric bus", "Supersonic airplane", "High-speed vacuum tube train", "A flying drone taxi"],
      solution: 2,
      cooldown: 5,
      time: 20,
    },
    {
      question: "FM radio is your lifeline during a zombie outbreak. What does “FM” stand for?",
      answers: ["Fast Messaging", "Frequency Modulation", "Frequency Mapping", "Field Monitoring"],
      solution: 1,
      cooldown: 5,
      time: 20,
    },
    {
      question: "Which new material is increasingly being used instead of silicon in modern fast chargers for better efficiency?",
      answers: ["Graphene", "Aluminum Nitride (AlN)", "Gallium Nitride (GaN)", "Copper"],
      solution: 2,
      cooldown: 5,
      time: 20,
    },
    {
      question: "What does HTTP stand for?",
      answers: ["HyperText Transfer Protocol", "HyperText Transfer Program", "HyperTransfer Text Protocol", "HyperText Transmission Protocol"],
      solution: 0,
      cooldown: 5,
      time: 20,
    },
    {
      question: "You hack into a hospital server during a zombie outbreak. Which attack tricks users into giving personal info?",
      answers: ["DDoS", "Man-in-the-Middle", "Phishing", "Brute Force"],
      solution: 2,
      cooldown: 5,
      time: 20,
    },
    {
      question: "In HTML, which tag is used to create a hyperlink?",
      answers: ["<link>", "<a>", "<href>", "<h>"],
      solution: 1,
      cooldown: 5,
      time: 20,
    },
    {
      question: "Most smartphones do not use fans to cool down. What do they primarily use instead?",
      answers: ["EM wave radiation", "Battery heat recycling", "Liquid nitrogen", "Graphite sheets / vapor chambers"],
      solution: 3,
      cooldown: 5,
      time: 20,
    },
    {
      question: "Why do OLED screens save more battery than LCDs on dark themes?",
      answers: ["Black implies lower processor usage", "OLED pixels emit their own light and turn off when black", "LCDs use solar charging in bright colors", "Dark colors reflect more light from the environment"],
      solution: 1,
      cooldown: 5,
      time: 20,
    },
    {
      question: "Why can some smartphones read fingerprints through a wet finger while others can’t?",
      answers: ["It depends on screen brightness", "Wet fingers increase skin conductivity", "Some phones use magnetic fingerprints", "Some sensors use ultrasonic waves instead of electrical conductivity"],
      solution: 3,
      cooldown: 5,
      time: 20,
    },
    {
      question: "What is the main purpose of a GPU in a computer?",
      answers: ["Managing memory", "Rendering graphics", "Cooling the CPU", "Storing files"],
      solution: 1,
      cooldown: 5,
      time: 20,
    },
    {
      question: "What unusual ingredient has been researched as a potential material for biodegradable batteries?",
      answers: ["Coffee powder", "Banana peels", "Crab shells", "Rice husk"],
      solution: 2,
      cooldown: 5,
      time: 20,
    },
    {
      question: "Which type of malware pretends to be useful software but actually harms the system?",
      answers: ["Worm", "Ransomware", "Spyware", "Trojan Horse"],
      solution: 3,
      cooldown: 5,
      time: 20,
    },
    {
      question: "What weird tech accessory did KFC release for gamers?",
      answers: ["A gaming console that keeps chicken warm", "Drumstick-shaped mouse", "A fried chicken-scented keyboard", "VR headset with gravy smell"],
      solution: 0,
      cooldown: 5,
      time: 20,
    },
    {
      question: "Which of these programming languages is primarily used for statistical computing and graphics?",
      answers: ["Go", "Python", "Swift", "R"],
      solution: 3,
      cooldown: 5,
      time: 20,
    },
    {
      question: "Which company developed the first microprocessor in 1971?",
      answers: ["Intel", "IBM", "AMD", "Microsoft"],
      solution: 0,
      cooldown: 5,
      time: 20,
    },
    {
      question: "Which protocol is mainly used to transfer emails between servers?",
      answers: ["FTP", "POP3", "IMAP", "SMTP"],
      solution: 3,
      cooldown: 5,
      time: 20,
    },
    {
      question: "In a zombie apocalypse, which cybersecurity measure helps protect your data when using public Wi-Fi?",
      answers: ["Firewall", "Antivirus", "VPN", "Adblocker"],
      solution: 2,
      cooldown: 5,
      time: 20,
    },
    {
      question: "What does the abbreviation PCIe stand for?",
      answers: ["Parallel Circuit Interface Extension", "Peripheral Component Interconnect Express", "Peripherals Communication Interconnect", "Program Control Interface Emitter"],
      solution: 1,
      cooldown: 5,
      time: 20,
    },
    {
      question: "Which unit measures the brightness of a display screen?",
      answers: ["Nits", "Lux", "Candela", "Lumen"],
      solution: 0,
      cooldown: 5,
      time: 20,
    },
    {
      question: "Which company first introduced the concept of a graphical user interface (GUI) for personal computers?",
      answers: ["Apple", "Xerox", "Microsoft", "IBM"],
      solution: 1,
      cooldown: 5,
      time: 20,
    },
    {
      question: "Which of these is NOT an operating system?",
      answers: ["Android", "Linux", "Oracle", "macOS"],
      solution: 2,
      cooldown: 5,
      time: 20,
    },
    {
      question: "In the context of computer memory, what does 'Volatile' mean?",
      answers: ["The memory can only be written once", "The memory loses its contents when the power is turned off", "The memory retains its data even when power is removed", "The memory is very fast"],
      solution: 1,
      cooldown: 5,
      time: 20,
    },
    {
      question: "Which of these file systems is most commonly used in modern Windows OS?",
      answers: ["ext4", "FAT32", "exFAT", "NTFS"],
      solution: 3,
      cooldown: 5,
      time: 20,
    },
    {
      question: "Which logic gate is called a 'universal gate'?",
      answers: ["NAND", "NAND", "OR", "XOR"],
      solution: 1,
      cooldown: 5,
      time: 20,
    },
    {
      question: "What does “URL” stand for?",
      answers: ["Universal Reference Link", "Unique Resource Link", "Uniform Resource Locator", "Uniform Reference Locator"],
      solution: 2,
      cooldown: 5,
      time: 20,
    },
    {
      question: "Which technology is used in credit cards and contactless payments?",
      answers: ["QR Code", "Bluetooth", "RFID", "Infrared"],
      solution: 2,
      cooldown: 5,
      time: 20,
    },
    {
      question: "Why do two phones with the same megapixel count produce very different photo quality?",
      answers: ["Sensor size, lens quality, and image processing matter more than megapixels", "Megapixels only affect video, not photos", "Phone brand determines quality", "Bigger phones always take better pictures"],
      solution: 0,
      cooldown: 5,
      time: 20,
    },
    {
      question: "When you 'delete' a file on your phone, what usually happens first?",
      answers: ["Data is instantly erased from memory", "Memory cells are physically destroyed", "File is copied to a hidden backup folder", "File pointers are removed, space marked as free"],
      solution: 3,
      cooldown: 5,
      time: 20,
    },
    {
      question: "Which popular programming language was originally called 'Oak'?",
      answers: ["C++", "Python", "Java", "Kotlin"],
      solution: 2,
      cooldown: 5,
      time: 20,
    },
    {
      question: "What odd object did Microsoft once try to use to store digital data?",
      answers: ["Glass", "Diamonds", "Salt", "Jelly"],
      solution: 0,
      cooldown: 5,
      time: 20,
    },
    {
      question: "In email communication, what does 'CC' stand for?",
      answers: ["Central communication", "Copy Contact", "Carbon Copy", "Common Channel"],
      solution: 2,
      cooldown: 5,
      time: 20,
    },
    {
      question: "What is the primary function of a quantum computer's 'qubit'?",
      answers: ["It can store more energy", "It operates at room temperature", "It can exist in a superposition of both 0 and 1 simultaneously", "It is much smaller in size"],
      solution: 2,
      cooldown: 5,
      time: 20,
    },
    {
      question: "What is the name for the small, ultra-efficient processing unit used in IoT devices?",
      answers: ["(NPU) Neural Processing Unit", "GPU (Graphics Processing Unit)", "FPU (Floating Point Unit)", "MCU (Microcontroller Unit)"],
      solution: 3,
      cooldown: 5,
      time: 20,
    },
    {
      question: "Which coding language was named after a comedy group?",
      answers: ["Go", "Kotlin", "Python", "Java"],
      solution: 2,
      cooldown: 5,
      time: 20,
    },
    {
      question: "Which component stores the BIOS firmware that helps the computer boot?",
      answers: ["CPU", "RAM", "GPU", "ROM"],
      solution: 3,
      cooldown: 5,
      time: 20,
    },
    {
      question: "What is the full form of ISP?",
      answers: ["Internal Service Process", "Internet Service Provider", "Intellectual Service Product", "Internet Streaming Platform"],
      solution: 1,
      cooldown: 5,
      time: 20,
    },
    {
      question: "In a zombie apocalypse, a bunch of zombies approach your house. You want to automatically secure your home - locking doors, turning on alarms etc. Which technology is going to help you?",
      answers: ["Machine Learning", "BlockChain", "IoT", "CyberSec"],
      solution: 2,
      cooldown: 5,
      time: 20,
    },
    {
      question: "What was the world’s first computer virus called?",
      answers: ["Creeper", "Trojan", "ILOVEYOU", "Brain"],
      solution: 0,
      cooldown: 5,
      time: 20,
    },
    {
      question: "Which video game character was originally called “Jumpman”?",
      answers: ["Sonic", "Mario", "Donkey Kong", "Link"],
      solution: 1,
      cooldown: 5,
      time: 20,
    },
  ],
}

// DONT CHANGE
export const GAME_STATE_INIT = {
  started: false,
  players: [],
  playersAnswer: [],
  manager: null,
  room: null,
  currentQuestion: 0,
  roundStartTime: 0,
  ...QUIZZ_CONFIG,
}
