export const WEBSOCKET_PUBLIC_URL = "http://localhost:5505/"
export const WEBSOCKET_SERVER_PORT = 5505

const QUIZZ_CONFIG = {
  password: "PASSWORD",
  subject: "Adobe",
  questions: [
    {
      question: "What does the .com in a website address usually mean?",
      answers: ["Commercial", "Communication", "Computer", "Community"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "In computing, what is a “bit”?",
      answers: ["The smallest unit of data", "A programming language", "A type of virus", "A hardware device"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "NASA might be your last hope to escape zombies; what does NASA stand for?",
      answers: ["National Aeronautics and Space Administration", "National Aerospace and Space Agency", "National Astronautical and Space Agency", "National Aeronautics and Science Association"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "What is Hyperloop, the transportation concept being developed by multiple companies?",
      answers: ["High-speed vacuum tube train", "Supersonic airplane", "Autonomous electric bus", "A flying drone taxi"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "FM radio is your lifeline during a zombie outbreak. What does “FM” stand for?",
      answers: ["Frequency Modulation", "Fast Messaging", "Frequency Mapping", "Field Monitoring"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "Which new material is increasingly being used instead of silicon in modern fast chargers for better efficiency?",
      answers: ["Gallium Nitride (GaN)", "Aluminum Nitride (AlN)", "Graphene", "Copper"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "What does HTTP stand for?",
      answers: ["HyperText Transfer Protocol", "HyperText Transfer Program", "HyperTransfer Text Protocol", "HyperText Transmission Protocol"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "You hack into a hospital server during a zombie outbreak. Which attack tricks users into giving personal info?",
      answers: ["Phishing", "Man-in-the-Middle", "DDoS", "Brute Force"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "In HTML, which tag is used to create a hyperlink?",
      answers: ["<a>", "<link>", "<href>", "<h>"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "Most smartphones do not use fans to cool down. What do they primarily use instead?",
      answers: ["Graphite sheets / vapor chambers", "Battery heat recycling", "Liquid nitrogen", "EM wave radiation"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "Why do OLED screens save more battery than LCDs on dark themes?",
      answers: ["OLED pixels emit their own light and turn off when black", "Black themes lower processor usage", "LCDs use solar charging in bright colors", "Dark colors reflect more light from the environment"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "Why can some smartphones read fingerprints through a wet finger while others can’t?",
      answers: ["Some sensors use ultrasonic waves instead of electrical conductivity", "Wet fingers increase skin conductivity", "Some phones use magnetic fingerprints", "It depends on screen brightness"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "What is the main purpose of a GPU in a computer?",
      answers: ["Rendering graphics", "Managing memory", "Cooling the CPU", "Storing files"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "What unusual ingredient has been researched as a potential material for biodegradable batteries?",
      answers: ["Crab shells", "Banana peels", "Coffee powder", "Rice husk"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "Which type of malware pretends to be useful software but actually harms the system?",
      answers: ["Trojan Horse", "Ransomware", "Spyware", "Worm"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "What weird tech accessory did KFC release for gamers?",
      answers: ["A gaming console that keeps chicken warm", "Drumstick-shaped mouse", "A fried chicken-scented keyboard", "VR headset with gravy smell"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "Which of these programming languages is primarily used for statistical computing and graphics?",
      answers: ["R", "Python", "Swift", "Go"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "Which company developed the first microprocessor in 1971?",
      answers: ["Intel", "IBM", "AMD", "Microsoft"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "Which protocol is mainly used to transfer emails between servers?",
      answers: ["SMTP", "POP3", "IMAP", "FTP"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "In a zombie apocalypse, which cybersecurity measure helps protect your data when using public Wi-Fi?",
      answers: ["VPN", "Antivirus", "Firewall", "Adblocker"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "What does the abbreviation PCIe stand for?",
      answers: ["Peripheral Component Interconnect Express", "Parallel Circuit Interface Extension", "Peripherals Communication Interconnect", "Program Control Interface Emitter"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "Which unit measures the brightness of a display screen?",
      answers: ["Nits", "Lux", "Candela", "Lumen"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "Which company first introduced the concept of a graphical user interface (GUI) for personal computers?",
      answers: ["Xerox", "Apple", "Microsoft", "IBM"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "Which of these is NOT an operating system?",
      answers: ["Oracle", "Linux", "Android", "macOS"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "In the context of computer memory, what does 'Volatile' mean?",
      answers: ["The memory loses its contents when the power is turned off", "The memory can only be written once", "The memory retains its data even when power is removed", "The memory is very fast"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "Which of these file systems is most commonly used in modern Windows OS?",
      answers: ["NTFS", "FAT32", "exFAT", "EXT4"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "Which logic gate is called a 'universal gate'?",
      answers: ["NAND", "AND", "OR", "XOR"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "What does “URL” stand for?",
      answers: ["Uniform Resource Locator", "Unique Resource Link", "Universal Reference Link", "Uniform Reference Locator"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "Which technology is used in credit cards and contactless payments?",
      answers: ["RFID", "Bluetooth", "QR code", "Infrared"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "Why do two phones with the same megapixel count produce very different photo quality?",
      answers: ["Sensor size, lens quality, and image processing matter more than megapixels", "Megapixels only affect video, not photos", "Phone brand determines quality", "Bigger phones always take better pictures"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "Most smartphones do not use fans to cool down. What do they primarily use instead?",
      answers: ["Graphite sheets / vapor chambers", "Battery heat recycling", "Liquid nitrogen", "EM wave radiation"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "When you 'delete' a file on your phone, what usually happens first?",
      answers: ["File pointers are removed, space marked as free", "Memory cells are physically destroyed", "File is copied to a hidden backup folder", "Data is instantly erased from memory"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "Which popular programming language was originally called 'Oak'?",
      answers: ["Java", "Python", "C++", "Kotlin"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "What odd object did Microsoft once try to use to store digital data?",
      answers: ["Glass", "Diamonds", "Salt", "Jelly"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "In email communication, what does 'CC' stand for?",
      answers: ["Carbon Copy", "Copy Contact", "Central Communication", "Common Channel"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "In digital electronics, which logic gate is called a 'universal gate'?",
      answers: ["NAND", "AND", "OR", "XOR"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "What is the primary function of a quantum computer's 'qubit'?",
      answers: ["It can exist in a superposition of both 0 and 1 simultaneously", "It operates at room temperature", "It can store more energy", "It is much smaller in size"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
    {
      question: "What is the name for the small, ultra-efficient processing unit used in IoT devices?",
      answers: ["MCU (Microcontroller Unit)", "GPU (Graphics Processing Unit)", "FPU (Floating Point Unit)", "NPU (Neural Processing Unit)"],
      solution: 0,
      cooldown: 5,
      time: 15,
    },
  ],
}

// DONT CHANGE
export const GAME_STATE_INIT = {
  started: false,
  players: [],
  playersAnswer: [],
  manager: null,
  room: null,
  currentQuestion: 0,
  roundStartTime: 0,
  ...QUIZZ_CONFIG,
}
